name: Continuous Delivery
run-name: CD run for ${{ github.actor }}
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            dist/*
    deliver:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Download artifacts
          uses: actions/download-artifact@v3
          with:
            name: artifacts
            path: dist
        - name: Login to GitHub Package Registry
          run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        - name: Build and push Docker image
          run: docker build -t ghcr.io/${{ github.repository }}:${{ github.sha }} . && docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
        - name: Push Docker image as latest
          run: docker tag ghcr.io/${{ github.repository }}:${{ github.sha }} ghcr.io/${{ github.repository }}:latest && docker push ghcr.io/${{ github.repository }}:latest